# Generated by Django 3.2.15 on 2024-11-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0138_rename_created_by_secteuractivite_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secteuractivite',
            options={'verbose_name': "Secteur d'activité", 'verbose_name_plural': "Secteurs d'activité"},
        ),
        migrations.AlterModelTable(
            name='secteuractivite',
            table='secteur_activite',
        ),
    ]
